const meals = [
  {day:'Mon',date:'8',breakfast:'Eggs & toast',lunch:'Chicken curry',snack:'Apple & yoghurt',dinner:'Curry leftovers',colour:'green'},
  {day:'Tue',date:'9',breakfast:'Yoghurt & berries',lunch:'Curry leftovers',snack:'Hummus & peppers',dinner:'Cook chicken curry',colour:'coral'},
  {day:'Wed',date:'10',breakfast:'Overnight oats',lunch:'Curry leftovers',snack:'Greek yoghurt',dinner:'Mediterranean chicken',colour:'purple'},
  {day:'Thu',date:'11',breakfast:'Eggs & spinach',lunch:'Chicken leftovers',snack:'Fruit & nuts',dinner:'Free evening',colour:'yellow'},
  {day:'Fri',date:'12',breakfast:'Yoghurt & fruit',lunch:'Tuna jacket potato',snack:'Hummus & carrots',dinner:'Cook tomato pasta bake',colour:'coral'},
  {day:'Sat',date:'13',breakfast:'Eggs & toast',lunch:'Pasta bake leftovers',snack:'Greek yoghurt',dinner:'Eat out',colour:'purple'},
  {day:'Sun',date:'14',breakfast:'Overnight oats',lunch:'Tuna jacket potato',snack:'Apple & peanut butter',dinner:'Plan next week',colour:'green'}
];
const groceries = {
  'Fruit & veg': [['Baby spinach', '200g', 1.25], ['Bell peppers', '3 pack', 1.59], ['Cherry tomatoes', '250g', 1.2], ['Onions', '1kg', 0.89]],
  'Protein': [['Chicken thighs', '1kg', 5.69], ['Tinned tuna', '4 pack', 3.45], ['Eggs', '12 pack', 2.45]],
  'Dairy & chilled': [['Greek yoghurt', '500g', 1.65], ['Grated cheese', '300g', 2.75]],
  'Cupboard & frozen': [['Brown rice', '1kg', 1.6], ['Chickpeas', '2 tins', 1.1], ['Coconut milk', '2 tins', 1.7], ['Frozen mixed veg', '1kg', 1.95]]
};
let currentLog = 'glucose'; let glucoseEntries = 0; let cookStep = 0; let onboardingStep = 1; let nextWeekMode = false;
const cookSteps = [
  ['Add 240 g brown rice and 500 ml water to a saucepan. Bring to the boil, cover, then turn to low heat for 25 minutes.', 'Use a measuring jug for liquids and kitchen scales for grams.', '240 g brown rice + 500 ml water', '25:00'],
  ['Heat 15 ml olive oil in a large pan on medium heat. Add 500 g diced chicken thighs and stir for 5–6 minutes.', 'The chicken is ready for the next step when it is white all the way through with no pink centre.', '15 ml olive oil + 500 g chicken', '06:00'],
  ['Add 150 g diced onion and 300 g sliced peppers. Cook for 4 minutes, then stir in 30 g Thai red curry paste.', 'Keep the heat at medium. Stir regularly so the curry paste does not catch on the base of the pan.', '150 g onion + 300 g peppers + 30 g curry paste', '04:00'],
  ['Pour in 400 ml light coconut milk and add 300 g frozen mixed vegetables. Simmer gently for 8 minutes.', 'A simmer means small, gentle bubbles—not a rolling boil.', '400 ml coconut milk + 300 g frozen vegetables', '08:00'],
  ['Stir in 100 g baby spinach for 1 minute until wilted. Divide the curry and rice into four equal portions.', 'Let portions cool slightly before refrigerating. Eat within 3 days, or freeze portions you will not eat.', '100 g baby spinach', '01:00']
];

function money(value){return `£${value.toFixed(2)}`}
function totalCost(){return Object.values(groceries).flat().reduce((sum, i) => sum + i[2], 0)}
function renderWeek(){const nextWeekDinners=['Chickpea & spinach curry','Chicken pesto pasta','Spicy lentil dhal','Free evening','One-pan chicken fajitas','Eat out','Use-up fried rice'];document.querySelector('#week-grid').innerHTML=meals.map((m,i)=>{let dinner=nextWeekMode?nextWeekDinners[i]:m.dinner;return `<article class="day-column ${i===1&&!nextWeekMode?'today-day':''}"><p class="day-name">${m.day.toUpperCase()}</p><div class="day-date">${nextWeekMode?Number(m.date)+7:m.date}</div><div class="planned-mini"><span>BREAKFAST</span>${m.breakfast}<button class="swap" data-swap="${i}" data-slot="breakfast">Swap ↻</button></div><div class="planned-mini coral-mini"><span>LUNCH</span>${m.lunch}<button class="swap" data-swap="${i}" data-slot="lunch">Swap ↻</button></div><div class="planned-mini yellow-mini"><span>SNACK</span>${m.snack}<button class="swap" data-swap="${i}" data-slot="snack">Swap ↻</button></div><div class="planned-mini ${m.colour}-mini"><span>DINNER</span>${dinner}<button class="swap" data-swap="${i}" data-slot="dinner">Swap ↻</button></div></article>`}).join('')}
function renderGroceries(){document.querySelector('#grocery-list').innerHTML=Object.entries(groceries).map(([group,items])=>`<section class="grocery-group"><h3>${group.toUpperCase()}</h3>${items.map(([name, amount, price],i)=>`<div class="grocery-item" data-name="${name}"><input class="check" type="checkbox" aria-label="Mark ${name} bought"><div><strong>${name}</strong><small>${amount} · Used by your plan</small></div><input class="price-input" type="number" step="0.01" value="${price.toFixed(2)}" aria-label="Price for ${name}"></div>`).join('')}</section>`).join('')}
function updateTotals(){let priceInputs=[...document.querySelectorAll('.price-input')];let total=priceInputs.reduce((s,i)=>s+(Number(i.value)||0),0);let profile=JSON.parse(localStorage.getItem('cookwellProfile')||'{}');let budget=profile.budget||40;document.querySelector('#shop-total').textContent=money(total);document.querySelector('#budget-spent').textContent=money(total);document.querySelector('#budget-spent').nextElementSibling.textContent=`of £${budget.toFixed(2)}`;document.querySelector('#budget-copy').textContent= total<=budget?`${money(budget-total)} left for your plan`:`${money(total-budget)} over your weekly budget`;document.querySelector('#budget-bar').style.width=`${Math.min(total/budget*100,100)}%`;let count=document.querySelectorAll('.check:checked').length;document.querySelector('#checked-count').textContent=`${count} / 13`}
function showScreen(name){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===name));document.querySelectorAll('[data-screen]').forEach(b=>b.classList.toggle('active',b.dataset.screen===name));const titles={today:['Tuesday, 9 September','A good day to start.'],plan:['YOUR WEEK','A plan that fits your life.'],shop:['SHOP & KITCHEN','Only buy what you will use.'],progress:['YOUR PROGRESS','Look for trends, not perfection.']};document.querySelector('#screen-eyebrow').textContent=titles[name][0];document.querySelector('#screen-title').textContent=titles[name][1];window.scrollTo({top:0,behavior:'smooth'})}
function openLog(kind){currentLog=kind;const d=document.querySelector('#log-dialog');const unit=document.querySelector('#log-unit');const timing=document.querySelector('#timing-label');const copy={glucose:['GLUCOSE LOG','Add a glucose reading','Record the value exactly as shown on your meter, including its unit.'],weight:['WEIGHT LOG','Add your weight','A weekly trend matters more than a single day.'],steps:['STEPS LOG','Add today’s steps','Manual logging now; Apple Health can come later.']}[kind];document.querySelector('#log-kind').textContent=copy[0];document.querySelector('#log-heading').textContent=copy[1];document.querySelector('#log-description').textContent=copy[2];unit.innerHTML=kind==='glucose'?'<option>mg/dL</option><option>mmol/L</option>':kind==='weight'?'<option>kg</option>':'<option>steps</option>';timing.hidden=kind!=='glucose';document.querySelector('#safety-note').hidden=kind!=='glucose';document.querySelector('#log-value').value='';d.showModal();document.querySelector('#log-value').focus()}
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('visible');setTimeout(()=>t.classList.remove('visible'),2600)}
function renderCook(){document.querySelector('#step-number').textContent=cookStep+1;document.querySelector('#cook-step').textContent=cookSteps[cookStep][0];document.querySelector('#cook-tip').textContent=cookSteps[cookStep][1];document.querySelector('#step-amount').textContent=cookSteps[cookStep][2];document.querySelector('#timer').textContent=cookSteps[cookStep][3];document.querySelector('#previous-step').style.visibility=cookStep===0?'hidden':'visible';document.querySelector('#next-step').textContent=cookStep===cookSteps.length-1?'Finish cooking ✓':'Next step →'}
function setOnboardingStep(step){onboardingStep=Math.max(1,Math.min(3,step));document.querySelectorAll('.onboard-step').forEach(section=>section.classList.toggle('active',Number(section.dataset.onboardingStep)===onboardingStep));document.querySelectorAll('.onboarding-progress span').forEach((bar,index)=>bar.classList.toggle('active',index<onboardingStep));document.querySelector('#onboard-back').style.visibility=onboardingStep===1?'hidden':'visible';document.querySelector('.onboarding-actions').classList.toggle('at-final',onboardingStep===3)}
function showOnboarding(){setOnboardingStep(1);document.querySelector('#onboarding-dialog').showModal()}
function applyOnboarding(){const name=document.querySelector('#onboard-name').value.trim();const budget=Number(document.querySelector('#onboard-budget').value)||40;const equipment=[...document.querySelectorAll('.equipment-grid input:checked')].map(input=>input.value);const profile={name,budget,equipment,dislikes:document.querySelector('#onboard-dislikes').value,likes:document.querySelector('#onboard-likes').value,exploration:document.querySelector('#onboard-exploration').value};localStorage.setItem('cookwellProfile',JSON.stringify(profile));document.querySelector('#budget-spent').nextElementSibling.textContent=`of £${budget.toFixed(2)}`;document.querySelector('#budget-copy').textContent=`£${(budget-totalCost()).toFixed(2)} left for your plan`;document.querySelector('#budget-bar').style.width=`${Math.min(totalCost()/budget*100,100)}%`;if(name)document.querySelector('#screen-title').textContent=`A good day to start, ${name}.`;document.querySelector('#inventory-plan-copy').textContent=`Your next plan will use what is left: brown rice, Greek yoghurt, chilli flakes and any groceries you mark as bought.`;document.querySelector('#onboarding-dialog').close();toast(`Your plan is ready${name?`, ${name}`:''}.`)}

renderWeek();renderGroceries();if(!localStorage.getItem('cookwellProfile'))showOnboarding();
document.addEventListener('click',e=>{const screen=e.target.closest('[data-screen]');if(screen)showScreen(screen.dataset.screen);const linked=e.target.closest('[data-screen-link]');if(linked)showScreen(linked.dataset.screenLink);if(e.target.matches('.profile-button'))showOnboarding();if(e.target.matches('#onboard-next'))setOnboardingStep(onboardingStep+1);if(e.target.matches('#onboard-back'))setOnboardingStep(onboardingStep-1);if(e.target.matches('#start-cooking,#cook-card')){document.querySelector('#recipe-dialog').showModal()}if(e.target.matches('#start-guided')){e.preventDefault();document.querySelector('#recipe-dialog').close();cookStep=0;renderCook();document.querySelector('#cook-dialog').showModal()}if(e.target.matches('#budget-details')){let spent=document.querySelector('#budget-spent').textContent;document.querySelector('#budget-dialog-spent').textContent=spent;document.querySelector('#budget-dialog-left').textContent=document.querySelector('#budget-copy').textContent.split(' ')[0];document.querySelector('#budget-dialog').showModal()}if(e.target.matches('#open-shop-from-budget')){e.preventDefault();document.querySelector('#budget-dialog').close();showScreen('shop')}if(e.target.matches('#build-next-week')){nextWeekMode=true;document.querySelector('#plan-week-label').textContent='16–22 SEPTEMBER';document.querySelector('#plan-title').textContent='Next week, using your kitchen';document.querySelector('#plan-subtitle').textContent='Breakfast, lunch, snack and dinner planned around what is already in your kitchen.';renderWeek();toast('Next week is built around your remaining inventory.')}if(e.target.matches('#swap-discovery'))toast('Mediterranean chicken swapped for spicy bean chilli.');if(e.target.matches('[data-swap]')){let card=e.target.closest('.planned-mini');let slot=e.target.dataset.slot;card.innerHTML=`<span>${slot.toUpperCase()}</span>Spicy bean chilli<button class="swap" data-slot="${slot}">Swap ↻</button>`;toast(`${slot[0].toUpperCase()+slot.slice(1)} swapped for a new option.`)}if(e.target.matches('[data-log],#open-log'))openLog(e.target.dataset.log||'glucose');if(e.target.matches('.tab')){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t===e.target));let isList=e.target.dataset.tab==='list';document.querySelector('#list-panel').classList.toggle('active',isList);document.querySelector('#inventory-panel').classList.toggle('active',!isList)}if(e.target.matches('#next-step')){if(cookStep<cookSteps.length-1){cookStep++;renderCook()}else{document.querySelector('#cook-dialog').close();toast('Batch meal marked cooked — nice work.')}}if(e.target.matches('#previous-step')&&cookStep>0){cookStep--;renderCook()}});
document.addEventListener('change',e=>{if(e.target.matches('.price-input'))updateTotals();if(e.target.matches('.check')){e.target.closest('.grocery-item').classList.toggle('checked',e.target.checked);updateTotals();if(e.target.checked)toast('Added to your kitchen.')}});
document.querySelector('#log-form').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;let value=document.querySelector('#log-value').value;if(!value){e.preventDefault();return}if(currentLog==='glucose'){glucoseEntries++;document.querySelector('#glucose-count').textContent=glucoseEntries;document.querySelector('#glucose-title').textContent=`${glucoseEntries} reading${glucoseEntries>1?'s':''} logged this week`;document.querySelector('#glucose-copy').textContent='Your entries stay unit-labelled. The app will surface longer-term patterns without giving medical instructions.'}toast('Entry saved.');});
document.querySelector('#onboarding-form').addEventListener('submit',e=>{e.preventDefault();applyOnboarding()});
